version: 2

sources:
  - name: dbt_database              # Snowflake database name
    schema: public                   # Schema name
    tables:
      - name: DBT_CONNECT_TEST       # The name of the table in Snowflake
        description: "Orders data containing information about customer orders."
        columns:
          - name: ROW_ID
            description: "Unique identifier for each row."
          - name: ORDER_ID
            description: "Unique identifier for each order."
          - name: ORDER_DATE
            description: "The date the order was placed."
          - name: SHIP_DATE
            description: "The date the order was shipped."
          - name: SHIP_MODE
            description: "The mode of shipping used for the order."
          - name: CUSTOMER_ID
            description: "Unique identifier for the customer."
          - name: CUSTOMER_NAME
            description: "Name of the customer."
          - name: SEGMENT
            description: "Segment of the customer (e.g., Consumer, Corporate)."
          - name: COUNTRY
            description: "Country where the customer is located."
          - name: CITY
            description: "City where the customer is located."
          - name: STATE
            description: "State where the customer is located."
          - name: POSTAL_CODE
            description: "Postal code of the customer's location."
          - name: REGION
            description: "Region where the customer is located."
          - name: PRODUCT_ID
            description: "Unique identifier for the product."
          - name: CATEGORY
            description: "Category of the product."
          - name: SUB_CATEGORY
            description: "Sub-category of the product."
          - name: PRODUCT_NAME
            description: "Name of the product."
          - name: SALES
            description: "Total sales amount for the order."
          - name: QUANTITY
            description: "Quantity of products sold in the order."
          - name: DISCOUNT
            description: "Discount applied to the order."
          - name: PROFIT
            description: "Profit made from the order."
          - name: PERSON
            description: "Person associated with the order (may require clarification)."
          - name: RETURNED
            description: "Indicates whether the order was returned (TRUE/FALSE)."

models:
  - name: dim_customers
    description: "This model pulls customer-related order data."
    columns:
      - name: ROW_ID
        description: "Unique identifier for each row."
      - name: ORDER_ID
        description: "Unique identifier for each order."
      - name: CUSTOMER_ID
        description: "Unique identifier for the customer."
      - name: CUSTOMER_NAME
        description: "Name of the customer."
      - name: SALES
        description: "Total sales amount for the order."
      - name: PROFIT
        description: "Profit made from the order."
